// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk_gCLWiLpoLTHghLlaCGSwmJId2dEn9g',
    appId: '1:347967088899:web:a01ce62df35e3cff7f6136',
    messagingSenderId: '347967088899',
    projectId: 'smarttravel-b6c68',
    authDomain: 'smarttravel-b6c68.firebaseapp.com',
    storageBucket: 'smarttravel-b6c68.firebasestorage.app',
    measurementId: 'G-C5YG6KH38K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk1l3mU9su0eXqvJqsHmfhBLkj_1QDNeg',
    appId: '1:347967088899:android:3521910b8387b6d77f6136',
    messagingSenderId: '347967088899',
    projectId: 'smarttravel-b6c68',
    storageBucket: 'smarttravel-b6c68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTwZZnPMzFYixQu1WATer7JARwBp2M0pg',
    appId: '1:347967088899:ios:e154de0ed32b7b2c7f6136',
    messagingSenderId: '347967088899',
    projectId: 'smarttravel-b6c68',
    storageBucket: 'smarttravel-b6c68.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTwZZnPMzFYixQu1WATer7JARwBp2M0pg',
    appId: '1:347967088899:ios:e154de0ed32b7b2c7f6136',
    messagingSenderId: '347967088899',
    projectId: 'smarttravel-b6c68',
    storageBucket: 'smarttravel-b6c68.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAk_gCLWiLpoLTHghLlaCGSwmJId2dEn9g',
    appId: '1:347967088899:web:83534e2267ce9b627f6136',
    messagingSenderId: '347967088899',
    projectId: 'smarttravel-b6c68',
    authDomain: 'smarttravel-b6c68.firebaseapp.com',
    storageBucket: 'smarttravel-b6c68.firebasestorage.app',
    measurementId: 'G-84CSQ4F4HY',
  );
}
